// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:mushaf_reader/src/data/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AyahModelAdapter());
    registerAdapter(JuzModelAdapter());
    registerAdapter(PageLayoutsAdapter());
    registerAdapter(SurahModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AyahModelAdapter());
    registerAdapter(JuzModelAdapter());
    registerAdapter(PageLayoutsAdapter());
    registerAdapter(SurahModelAdapter());
  }
}
