// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:mushaf_reader/src/data/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AyahAdapter());
    registerAdapter(JuzAdapter());
    registerAdapter(PageLayoutsAdapter());
    registerAdapter(RevelationTypeAdapter());
    registerAdapter(SurahAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AyahAdapter());
    registerAdapter(JuzAdapter());
    registerAdapter(PageLayoutsAdapter());
    registerAdapter(RevelationTypeAdapter());
    registerAdapter(SurahAdapter());
  }
}
